baseURL = "https://kuoforit.github.io/"
theme = "risotto"
title = "kuoforit"
author = "TBD"
copyright = "© kuoforit"
enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]

sectionPagesMenu = "main"

defaultContentLanguage = "zh-tw"
defaultContentLanguageInSubdir = false

[languages]
  [languages.zh-tw]
    label = "繁體中文"
    weight = 1
  [languages.ja]
    label = "日本語"
    weight = 2
  [languages.en]
    label = "EN"
    weight = 3

[pagination]
pagerSize = 10

[params]
noindex = false

[params.theme]
palette = "tokyo-night-light"

[params.about]
title = "kuoforit"
description = "Steven Kuo的文字檔案館<br>Steven Kuo's archive"
logo = "📝"

[[params.socialLinks]]
icon = "fa-brands fa-x-twitter"
title = "X"
url = "https://x.com/kuoforit"

[[params.socialLinks]]
icon = "fa-brands fa-instagram"
title = "Instagram"
url = "https://www.instagram.com/kuoforit/"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.renderer]
unsafe = true

[markup]

  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = true
